#!/bin/bash

### author: Vladimir Ryazansev
### mail: 361elfforest@gmail.com

## TODO Вынести сылки до скачивания о отдельный файл для изменение версий

set -uo pipefail

##
SCRIPT="`dirname "$(readlink -f $0)"`"
export ROOT="$SCRIPT"

##
export PERSON=${ROOT}/person.conf
source ${PERSON}



## Устоновка emacs 28
function emacs() {
  if [[ ! -f /bin/emacs ]]; then
    sudo add-apt-repository ppa:kelleyk/emacs
    sudo update
    sudo apt install -y emacs28
  fi
}

## Превращение файлов org-mode в исходный код
function emacsLoadOrgFile() {
    if [[ -d  ${ROOT}/src-literal ]]; then
	##
	if [ -d ${ROOT}/src-literal ]; then
	    for i in ${ROOT}/src-literal/*.org; do
		if [ -r $i ]; then
		    echo "действие с файлом: ${i}"
		    emacs --batch --no-init --eval "(progn (require 'org))"
		fi
	    done
	    unset i
	fi
    else
	echo "Нет папки с исходным кодом ${ROOT}/src-literal"
    fi
}

## устоновка lisp и quicklisp
function lisp() {
    if [[ ! -f /bin/sbcl ]]; then
       sudo apt install -y sbcl
       
    fi

    if [[ ! -f ${HOME}/.sbclrc ]]; then
	curl -O https://beta.quicklisp.org/quicklisp.lisp
	sbcl --eval "(load \"quicklisp.lisp\")"\
	     --eval "(quicklisp-quickstart:install)"\
	     --eval "(ql:add-to-init-file)"\
	     --eval "(quit)"
    fi
}

## Javasript
function js(){
    local module_local=$HOME/.global-modules
    if [[ ! -f ${HOME}/.npmrc ]]; then
	mkdir -p $module_local
	npm config set prefix "${module_local}"
	npm config set init.author.name "${_AUTHOR}"
	npm config set init.author.email "${_MAIL}"
	
	if [[ -f /bin/zsh ]]; then
            echo -e "\n\nexport PATH=$GLOBAL_MODULES/bin:$PATH" >> ~/.zshrc
            source ~/.zshrc
	fi

	echo -e "\n\nexport PATH=$GLOBAL_MODULES/bin:$PATH" >> ~/.bashrc
    fi
    
}

## Гланая функция
function main() {
    source ${ROOT}/programList.list
    local array=(${_PROGRAM_LIST})
    for item in ${array[*]}
    do
	sudo apt install -y $item
    done
    emacs
    lisp
    emacsLoadOrgFile
    js
}


## меню дейсвий
function mainmenu() {
    echo -ne "
MAIN MENU
1) Устоновка программ
2) Конвертация файлов org-mode в исходники. 
0) Exit
Choose an option:  "
    read -r ans
    case $ans in
    1)
        main
        ;;
    2)
        emacsLoadOrgFile
        ;;
    0)
        echo "Bye bye."
        exit 0
        ;;
    *)
        echo "Wrong option."
        exit 1
        ;;
    esac
}

mainmenu

